import React, { useEffect, useState } from 'react';
import { AEReport } from '../services/aeReport';
import { CaseWork, WorkInput, WorkResult, getCaseWork, saveCaseWork, workUsers, getWorkbench, getNotifications, readNotifications, Workbench, InAppNotification } from '../services/caseWork';
import { matchesWork } from '../services/caseWorkModel.js';
import { hasRemoteEndpoint } from '../services/aeApi';
import { useT } from '../i18n/LangContext';
const inputClass = 'w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 p-2 text-sm';
const buttonClass = 'rounded-lg px-3 py-2 bg-indigo-600 text-white text-sm disabled:opacity-40';
const taipeiToday = () => { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Taipei', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const get = (type: string) => parts.find(part => part.type === type)?.value; return `${get('year')}-${get('month')}-${get('day')}`; };
export default function CaseWorkBoard({ cases, actor }: { cases: AEReport[]; actor: string }) {
 const t = useT(), remote = hasRemoteEndpoint();
 const [records, setRecords] = useState<Record<string, WorkResult>>({}), [users, setUsers] = useState<string[]>([]), [board, setBoard] = useState<Workbench | null>(null), [scope, setScope] = useState<'today'|'week'|'overdue'>('today');
 const [notifications, setNotifications] = useState<InAppNotification[]>([]), [id, setId] = useState(''), [draft, setDraft] = useState<CaseWork | null>(null), [busy, setBusy] = useState(false), [loaded, setLoaded] = useState(false), [dirty, setDirty] = useState(false), [message, setMessage] = useState('');
 const error = (e: any) => setMessage(t(e.message === 'WORK_CONFLICT' ? 'work.conflict' : e.message === 'INVALID_WORK' || e.message === 'INVALID_CANCEL_REASON' || e.message === 'INVALID_TRANSITION' ? 'work.invalid' : 'work.error'));
 const refresh = async (nextScope = scope) => { setBusy(true); try { const options = await workUsers(); if (remote) { const [b, n] = await Promise.all([getWorkbench(nextScope), getNotifications()]); setBoard(b); setNotifications(n.notifications); } else { const next: Record<string, WorkResult> = {}; for (const c of cases) next[c.id] = await getCaseWork(c.id); setRecords(next); } setUsers(options); setLoaded(true); setMessage(''); } catch (e) { error(e); } finally { setBusy(false); } };
 useEffect(() => { refresh(); }, [scope]);
 useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
 const edit = (patch: Partial<CaseWork>) => { setDraft({ ...draft!, ...patch }); setDirty(true); setMessage(''); };
 const open = async (next: string) => { if (dirty) { setMessage(t('work.dirty')); return; } setBusy(true); try { const result = await getCaseWork(next); setRecords(v => ({ ...v, [next]: result })); setId(next); setDraft(structuredClone(result.work)); setMessage(''); } catch (e) { error(e); } finally { setBusy(false); } };
 const save = async () => { if (!draft) return; setBusy(true); try { const result = await saveCaseWork(id, draft as WorkInput); setRecords(v => ({ ...v, [id]: result })); setDraft(result.work); setDirty(false); setMessage(t('work.saved')); await refresh(); } catch (e) { error(e); } finally { setBusy(false); } };
 const markRead = async () => { const ids = notifications.filter(n => !n.readAt).map(n => n.id); if (!ids.length) return; setBusy(true); try { await readNotifications(ids); setNotifications(v => v.map(n => ids.includes(n.id) ? { ...n, readAt: new Date().toISOString() } : n)); } catch (e) { error(e); } finally { setBusy(false); } };
 const displayed = remote ? (board?.items || []) : cases.filter(c => records[c.id] && matchesWork(records[c.id].work, 'all', remote ? actor : 'local-demo', taipeiToday())).map(c => ({ caseId: c.id, caseNumber: c.caseNumber || c.id, ...records[c.id].work, overdue: !!records[c.id].work.workDueDate && records[c.id].work.workDueDate < taipeiToday() }));
 const unread = notifications.filter(n => !n.readAt).length;
 return <details className="m-3 rounded-xl border border-indigo-200 dark:border-indigo-800 p-3"><summary className="font-bold cursor-pointer">{t('work.title')} {remote && unread ? `(${unread})` : ''}</summary>
  <p className="text-xs font-bold my-2 text-slate-700 dark:text-slate-200">{t('work.subtitle')}</p><p className="text-xs my-2 text-slate-600 dark:text-slate-300">{t('work.note')}</p>{!remote && <p className="text-amber-800 dark:text-amber-300 text-xs">{t('work.demo')}</p>}
  <div role="status" aria-live="polite" className="text-sm my-2">{message}</div>
  {remote && <section aria-label={t('work.notifications')} className="text-xs border rounded p-2 my-2"><b>{t('work.notifications')} · {unread}</b><span className="ml-2">{t('work.refreshOnly')}</span>{notifications.length > 0 && <><ul>{notifications.slice(0, 10).map(n => <li key={n.id}>{n.kind === 'work_due' ? t('work.dueNotice') : t('work.assignedNotice')} · {n.createdAt}{n.readAt ? ` · ${t('work.read')}` : ''}</li>)}</ul><button className={buttonClass} disabled={busy || !unread} onClick={markRead}>{t('work.markRead')}</button></>}</section>}
  <div className="flex gap-2 flex-wrap">{(['today','week','overdue'] as const).map(s => <button key={s} aria-pressed={scope === s} className={buttonClass} onClick={() => { if (!dirty) setScope(s); else setMessage(t('work.dirty')); }}>{t(`work.${s}`)}</button>)}<button disabled={busy} className={buttonClass} onClick={() => refresh()}>{t('work.reload')}</button></div>
  {board && <p className="text-xs my-2">{t('work.timezone')}: {board.timezone} · {board.from} – {board.to} · {t('work.week')}: {board.weekStart} – {board.weekEnd}</p>}
  {!loaded ? <p>{t('work.loading')}</p> : <div className="flex gap-2 flex-wrap my-3">{displayed.length ? displayed.map((w: any) => <button disabled={busy} key={w.caseId} className={buttonClass} onClick={() => open(w.caseId)}>{w.caseNumber} · {t(`work.status.${w.status || 'todo'}`)} · {w.assignee || t('work.unassigned')} · {w.workDueDate} {w.overdue ? `· ${t('work.overdue')}` : ''}</button>) : <p>{t('work.empty')}</p>}</div>}
  {draft && <fieldset disabled={busy} className="space-y-3"><legend className="font-bold">{id} · v{draft.version}{dirty ? ' *' : ''}</legend><p className="text-xs">{t('work.statusSeparate')}</p>
   <label className="block">{t('work.status')}<select className={inputClass} value={draft.status} onChange={e => edit({ status: e.target.value as CaseWork['status'] })}>{(['todo','in-progress','waiting','completed','cancelled'] as const).map(s => <option key={s} value={s}>{t(`work.status.${s}`)}</option>)}</select></label>
   {draft.status === 'cancelled' && <label className="block">{t('work.cancelReason')}<textarea required maxLength={500} className={inputClass} value={draft.cancelReason || ''} onChange={e => edit({ cancelReason: e.target.value })}/></label>}
   <label className="block">{t('work.owner')}<select className={inputClass} value={draft.assignee} onChange={e => edit({ assignee: e.target.value })}><option value="">{t('work.unassigned')}</option>{[...new Set([...users, ...(draft.assignee ? [draft.assignee] : [])])].map(u => <option key={u}>{u}</option>)}</select></label>
   <label className="block">{t('work.next')}<textarea maxLength={1000} className={inputClass} value={draft.nextAction} onChange={e => edit({ nextAction: e.target.value })}/></label><label className="block">{t('work.due')}<input type="date" className={inputClass} value={draft.workDueDate} onChange={e => edit({ workDueDate: e.target.value })}/></label>
   <h4 className="font-bold">{t('work.items')}</h4>{draft.items.map((item, i) => <div key={item.id} className="flex gap-2"><input aria-label={t('work.items')} maxLength={300} className={inputClass} value={item.title} onChange={e => edit({ items: draft.items.map((v, j) => j === i ? { ...v, title: e.target.value } : v) })}/><select aria-label={t('work.items')} className={inputClass} value={item.status} onChange={e => edit({ items: draft.items.map((v, j) => j === i ? { ...v, status: e.target.value } : v) })}>{(['pending','received','cancelled'] as const).map(s => <option key={s} value={s}>{t(`work.${s}`)}</option>)}</select></div>)}<button type="button" className={buttonClass} disabled={draft.items.length >= 50} onClick={() => edit({ items: [...draft.items, { id: crypto.randomUUID(), title: '', status: 'pending' }] })}>{t('work.addItem')}</button>
   <h4 className="font-bold">{t('work.contacts')}</h4>{draft.contacts.map((contact, i) => <div key={contact.id} className="border rounded-lg p-2 space-y-2">{(['date','result','nextFollowUp'] as const).map(key => <label key={key} className="block">{t(key === 'nextFollowUp' ? 'work.follow' : `work.${key}`)}<input className={inputClass} type={key === 'result' ? 'text' : 'date'} maxLength={1000} value={contact[key]} onChange={e => edit({ contacts: draft.contacts.map((v, j) => j === i ? { ...v, [key]: e.target.value } : v) })}/></label>)}<label className="block">{t('work.method')}<select className={inputClass} value={contact.method} onChange={e => edit({ contacts: draft.contacts.map((v, j) => j === i ? { ...v, method: e.target.value } : v) })}>{(['phone','email','visit','other'] as const).map(m => <option key={m} value={m}>{t(`work.${m}`)}</option>)}</select></label></div>)}<button type="button" className={buttonClass} disabled={draft.contacts.length >= 100} onClick={() => edit({ contacts: [...draft.contacts, { id: crypto.randomUUID(), date: taipeiToday(), method: 'phone', result: '', nextFollowUp: '' }] })}>{t('work.addContact')}</button>
   <button className={buttonClass} disabled={!dirty || (draft.status === 'cancelled' && !draft.cancelReason?.trim())} onClick={save}>{t('work.save')}</button>
   <h4>{t('work.audit')}</h4><ul className="text-xs">{records[id]?.audit.map(a => <li key={a.version}>v{a.version} · {a.at} · {a.actor} · {a.action}</li>)}</ul></fieldset>}
 </details>;
}
