import { emptyWork, validateWork } from '../services/caseWorkModel.js';

export async function handleWork(request, env, seg, role, actor, cors) {
  const reply = (data, status = 200) => new Response(JSON.stringify(data), { status, headers: { ...cors, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } });
  // Check before any query: neither user directory nor work data is visible to reps.
  if (role !== 'pv') return reply({ error: 'forbidden' }, 403);
  const users = async () => {
    const { results } = await env.DB.prepare("SELECT email FROM ae_users WHERE lower(trim(role)) = 'pv' ORDER BY email").all();
    return [...new Set([...(results || []).map(r => r.email.trim().toLowerCase()), ...(env.AE_PV_EMAILS || '').split(',').map(s => s.trim().toLowerCase()).filter(Boolean)])];
  };
  try {
    if (seg.length === 1 && seg[0] === 'work-users') {
      if (request.method !== 'GET') return reply({ error: 'method not allowed' }, 405);
      return reply({ users: await users() });
    }
    const caseId = decodeURIComponent(seg[0]);
    if (request.method !== 'GET' && request.method !== 'PUT') return reply({ error: 'method not allowed' }, 405);
    const row = await env.DB.prepare('SELECT id FROM ae_cases WHERE id = ? AND deleted_at IS NULL').bind(caseId).first();
    if (!row) return reply({ error: 'not found' }, 404);
    if (request.method === 'GET') {
      const work = await env.DB.prepare('SELECT payload, version FROM ae_case_work WHERE case_id = ?').bind(caseId).first();
      const { results } = await env.DB.prepare('SELECT version, at, actor, action FROM ae_work_audit WHERE case_id = ? ORDER BY version DESC LIMIT 100').bind(caseId).all();
      return reply({ work: work ? { ...JSON.parse(work.payload), version: work.version } : emptyWork(), audit: results || [] });
    }
    // Bounded streaming read, including requests without Content-Length.
    const reader = request.body?.getReader();
    if (!reader) return reply({ error: 'invalid body' }, 400);
    let length = 0; const chunks = [];
    while (true) {
      const { done, value } = await reader.read(); if (done) break;
      length += value.byteLength;
      if (length > 200000) { await reader.cancel(); return reply({ error: 'body too large' }, 413); }
      chunks.push(value);
    }
    const bytes = new Uint8Array(length); let offset = 0;
    for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; }
    let work;
    try { work = validateWork(JSON.parse(new TextDecoder().decode(bytes))); }
    catch { return reply({ error: 'INVALID_WORK' }, 400); }
    if (work.assignee && !(await users()).includes(work.assignee)) return reply({ error: 'INVALID_ASSIGNEE' }, 400);
    const version = work.version; work.version++;
    const now = new Date().toISOString();
    // One conditional statement; audit is generated by triggers in the same transaction.
    const result = await env.DB.prepare(`INSERT INTO ae_case_work(case_id, version, payload, updated_at, updated_by)
      SELECT ?, ?, ?, ?, ? WHERE EXISTS(SELECT 1 FROM ae_cases WHERE id = ? AND deleted_at IS NULL)
      AND (? = 0 OR EXISTS(SELECT 1 FROM ae_case_work WHERE case_id = ?))
      ON CONFLICT(case_id) DO UPDATE SET version=excluded.version,payload=excluded.payload,updated_at=excluded.updated_at,updated_by=excluded.updated_by
      WHERE ae_case_work.version = ?`).bind(caseId, work.version, JSON.stringify(work), now, actor, caseId, version, caseId, version).run();
    if (!result.meta?.changes) return reply({ error: 'WORK_CONFLICT' }, 409);
    return reply({ work, audit: [{ version: work.version, at: now, actor, action: 'work_saved' }] });
  } catch {
    return reply({ error: 'work backend unavailable' }, 500);
  }
}
